In [1]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df =1)



In [2]:
contents = ['메리랑 놀러가고 싶지만 바쁜데 어떡하죠?',
            '메리는 공원에서 산책하고 노는 것을 싫어해요', 
            '메리는 공원에서 노는 것도 싫어해요. 이상해요',
            '먼 곳으로 여행을 떠나고 싶은데 너무 바빠서 그러질 못하고 있어요']


In [3]:

X = vectorizer.fit_transform(contents)
vectorizer.get_feature_names()

['것도',
 '것을',
 '곳으로',
 '공원에서',
 '그러질',
 '너무',
 '노는',
 '놀러가고',
 '떠나고',
 '메리는',
 '메리랑',
 '못하고',
 '바빠서',
 '바쁜데',
 '산책하고',
 '싫어해요',
 '싶은데',
 '싶지만',
 '어떡하죠',
 '여행을',
 '이상해요',
 '있어요']

In [6]:
X.toarray().transpose()

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [7]:
from konlpy.tag import Twitter
t = Twitter()


In [8]:
contents_tokens = [t.morphs(row) for row in contents]
contents_tokens

[['메리', '랑', '놀러', '가고', '싶지만', '바쁜데', '어떡하죠', '?'],
 ['메리', '는', '공원', '에서', '산책', '하고', '노', '는', '것', '을', '싫어해요'],
 ['메리', '는', '공원', '에서', '노', '는', '것', '도', '싫어해요', '.', '이상해요'],
 ['먼',
  '곳',
  '으로',
  '여행',
  '을',
  '떠나고',
  '싶은데',
  '너무',
  '바빠서',
  '그러질',
  '못',
  '하고',
  '있어요']]

In [9]:
contents_for_vectorize = []

for content in contents_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    contents_for_vectorize.append(sentence)

contents_for_vectorize

[' 메리 랑 놀러 가고 싶지만 바쁜데 어떡하죠 ?',
 ' 메리 는 공원 에서 산책 하고 노 는 것 을 싫어해요',
 ' 메리 는 공원 에서 노 는 것 도 싫어해요 . 이상해요',
 ' 먼 곳 으로 여행 을 떠나고 싶은데 너무 바빠서 그러질 못 하고 있어요']

In [24]:
X = vectorizer.fit_transform(contents_for_vectorize)
num_samples, numfeatures = X.shape
num_samples, numfeatures

(4, 20)

In [15]:
vectorizer.get_feature_names()

['가고',
 '공원',
 '그러질',
 '너무',
 '놀러',
 '떠나고',
 '메리',
 '바빠서',
 '바쁜데',
 '산책',
 '싫어해요',
 '싶은데',
 '싶지만',
 '어떡하죠',
 '에서',
 '여행',
 '으로',
 '이상해요',
 '있어요',
 '하고']

In [16]:
X.toarray().transpose()

array([[1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1]], dtype=int64)

In [18]:
new_post = ['메리랑 공원에서 산책하고 놀고 싶어요']
new_post_tokens = [t.morphs(row) for row in new_post]

new_post_for_vectorize = []

for content in new_post_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    new_post_for_vectorize.append(sentence)

new_post_for_vectorize

[' 메리 랑 공원 에서 산책 하고 놀고 싶어요']

In [19]:
new_post_vec = vectorizer.transform(new_post_for_vectorize)
new_post_vec.toarray()


array([[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]],
      dtype=int64)

In [26]:
import scipy as sp 

def dist_raw(v1,v2):
    delta = v1 - v2
    return sp.linalg.norm(delta.toarray())

In [28]:
best_doc = None 
best_dist = 65535
best_i = None


In [29]:
for i in range(0, num_samples):
    post_vec = X.getrow(i)
    d = dist_raw(post_vec, new_post_vec)

    print("== Post %i with dist=%.2f    :  %s" %(i,d,contents[i]))

    if d<best_dist:
        best_dist = d
        best_i = i

== Post 0 with dist=3.00    :  메리랑 놀러가고 싶지만 바쁜데 어떡하죠?
== Post 1 with dist=1.00    :  메리는 공원에서 산책하고 노는 것을 싫어해요
== Post 2 with dist=2.00    :  메리는 공원에서 노는 것도 싫어해요. 이상해요
== Post 3 with dist=3.46    :  먼 곳으로 여행을 떠나고 싶은데 너무 바빠서 그러질 못하고 있어요


In [32]:
post_vec

<1x20 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [33]:
new_post_vec

<1x20 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [34]:
X

<4x20 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [35]:
print("Best post is %i, dist = %.2f" % (best_i, best_dist))
print("-->", new_post)
print('----->', contents[best_i])

Best post is 1, dist = 1.00
--> ['메리랑 공원에서 산책하고 놀고 싶어요']
-----> 메리는 공원에서 산책하고 노는 것을 싫어해요


In [36]:
for i in range(0,len(contents)):
    print(X.getrow(i).toarray())

print('--------------')
print(new_post_vec.toarray())

[[1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0]]
[[0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1]]
[[0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0]]
[[0 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 1 1]]
--------------
[[0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1]]


In [37]:
def dist_norm(v1,v2):
    v1_normalized = v1 / sp.linalg.norm(v1.toarray())
    v2_normalized = v2 / sp.linalg.norm(v2.toarray())
    
    delta = v1_normalized - v2_normalized

    return sp.linalg.norm(delta.toarray())

In [39]:
for i in range(0,num_samples):
    post_vec = X.getrow(i)
    d = dist_norm(post_vec, new_post_vec)
      
    print("== Post %i with dist=%.2f    :  %s" %(i,d,contents[i]))

    if d<best_dist:
        best_dist = d
        best_i = i

== Post 0 with dist=1.28    :  메리랑 놀러가고 싶지만 바쁜데 어떡하죠?
== Post 1 with dist=0.42    :  메리는 공원에서 산책하고 노는 것을 싫어해요
== Post 2 with dist=0.89    :  메리는 공원에서 노는 것도 싫어해요. 이상해요
== Post 3 with dist=1.30    :  먼 곳으로 여행을 떠나고 싶은데 너무 바빠서 그러질 못하고 있어요


In [40]:
print("Best post is %i, dist = %.2f" % (best_i, best_dist))
print("-->", new_post)
print('----->', contents[best_i])

Best post is 1, dist = 0.42
--> ['메리랑 공원에서 산책하고 놀고 싶어요']
-----> 메리는 공원에서 산책하고 노는 것을 싫어해요


In [43]:
def tfidf(t,d,D):
    tf = float(d.count(t)) / sum(d.count(w) for w in set(d))
    idf = sp.log( float(len(D))/(len([doc for doc in D if t in doc])) )
    return tf, idf

In [48]:
a, abb, abc = ['a'], ['a','b','b'],['a','b','c']
D = [a,abb,abc]

print(tfidf('a',a,D))
print(tfidf('b',abb,D))
print(tfidf('a',abc,D))
print(tfidf('b',abc,D))
print(tfidf('c',abc,D))

(1.0, 0.0)
(0.6666666666666666, 0.4054651081081644)
(0.3333333333333333, 0.0)
(0.3333333333333333, 0.4054651081081644)
(0.3333333333333333, 1.0986122886681098)


In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=1, decode_error='ignore')

In [59]:
contents_tokens = [t.morphs(row) for row in contents]

contents_for_vectorize = []

for content in contents_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    contents_for_vectorize.append(sentence)

contents_for_vectorize


X = vectorizer.fit_transform(contents_for_vectorize)
num_samples, numfeatures = X.shape
num_samples, numfeatures

(4, 20)

In [60]:
vectorizer.get_feature_names()

['가고',
 '공원',
 '그러질',
 '너무',
 '놀러',
 '떠나고',
 '메리',
 '바빠서',
 '바쁜데',
 '산책',
 '싫어해요',
 '싶은데',
 '싶지만',
 '어떡하죠',
 '에서',
 '여행',
 '으로',
 '이상해요',
 '있어요',
 '하고']

In [64]:
new_post = ['근처 공원에 메리랑 놀러가고 싶네요.']
new_post_tokens = [t.morphs(row) for row in new_post]

new_post_for_vectorize = []

for content in new_post_tokens:
    sentence = ''
    for word in content:
        sentence = sentence + ' ' + word
        
    new_post_for_vectorize.append(sentence)

new_post_for_vectorize


[' 근처 공원 에 메리 랑 놀러 가고 싶네요 .']

In [65]:
new_post_vec = vectorizer.transform(new_post_for_vectorize)

In [66]:
best_doc = None 
best_dist = 65535
best_i = None


for i in range(0,num_samples):
    post_vec = X.getrow(i)
    d = dist_norm(post_vec, new_post_vec)
      
    print("== Post %i with dist=%.2f    :  %s" %(i,d,contents[i]))

    if d<best_dist:
        best_dist = d
        best_i = i


print("Best post is %i, dist = %.2f" % (best_i, best_dist))
print("-->", new_post)
print('----->', contents[best_i])

== Post 0 with dist=0.90    :  메리랑 놀러가고 싶지만 바쁜데 어떡하죠?
== Post 1 with dist=1.18    :  메리는 공원에서 산책하고 노는 것을 싫어해요
== Post 2 with dist=1.16    :  메리는 공원에서 노는 것도 싫어해요. 이상해요
== Post 3 with dist=1.41    :  먼 곳으로 여행을 떠나고 싶은데 너무 바빠서 그러질 못하고 있어요
Best post is 0, dist = 0.90
--> ['근처 공원에 메리랑 놀러가고 싶네요.']
-----> 메리랑 놀러가고 싶지만 바쁜데 어떡하죠?
